package org.example;
import javax.swing.*;

public class DemoFrame{

    public JFrame frame;
    public JLabel label1;
    public JLabel label2;
    public JLabel label3;
    public JLabel label4;
    public JTextField name;
    public String movienames;
    public String descriptions;
    public String comments;
    public String ratings;
    public JTextArea description;
    public JCheckBox box1;
    public JCheckBox box2;
    public JCheckBox box3;
    public JCheckBox box4;
    public JCheckBox box5;
    public JTextArea comment;
    public JButton button;
    public JPanel panel1;
    public JPanel panel2;
    public JPanel panel3;
    public JPanel panel4;
    public JPanel panel5;
    public DemoFrame() throws Exception{
        frame = new JFrame("complete information");
        frame.setLayout(null);
        frame.setSize( 700, 1000);
        frame.setVisible(true);
        panel1 = new JPanel();
        panel1.setLocation(0,0);
        panel1.setSize(700,100);
        label1=  new JLabel("Movie Name:");
        name = new JTextField(movienames,  30);
        name.setEditable(true);
        panel1.add(label1);
        panel1.add(name);
        frame.add(panel1);
        panel2 = new JPanel();
        panel2.setLocation(0,100);
        panel2.setSize(700,200);
        label2 = new JLabel("Description:");
        description = new JTextArea(descriptions, 5, 30);
        description.setEditable(true);
        description.setLineWrap(true);
        description.setWrapStyleWord(true);
        panel2.add(label2);
        panel2.add(description);
        frame.add(panel2);
        panel3 = new JPanel();
        panel3.setSize(700,100);
        panel3.setLocation(0,300);
        label3 = new JLabel("Your Rating:");
        box1 = new JCheckBox("1");
        box2 = new JCheckBox("2");
        box3 = new JCheckBox("3");
        box4 = new JCheckBox("4");
        box5 = new JCheckBox("5");
        panel3.add(label3);
        panel3.add(box1);
        panel3.add(box2);
        panel3.add(box3);
        panel3.add(box4);
        panel3.add(box5);
        frame.add(panel3);
        panel4 = new JPanel();
        panel4.setLocation(0,400);
        panel4.setSize(700,200);
        label4 = new JLabel("Your Comments:");
        comment = new JTextArea(comments,5,30);
        comment.setEditable(true);
        comment.setLineWrap(true);
        comment.setWrapStyleWord(true);
        panel4.add(label4);
        panel4.add(comment);
        frame.add(panel4);
        panel5 = new JPanel();
        panel5.setLocation(0,600);
        panel5.setSize(700,100);
        button = new JButton("Add");
        panel5.add(button);
        frame.add(panel5);
        frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
    }
    public static void main(String[] args) throws Exception{
        DemoFrame df = new DemoFrame();
    }
}